/*
 * Copyright 2016 Red Hat Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.vertx.mqtt;

import io.netty.handler.codec.mqtt.MqttVersion;
import io.vertx.codegen.annotations.DataObject;
import io.vertx.codegen.annotations.GenIgnore;
import io.vertx.codegen.json.annotations.JsonGen;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonObject;
import io.vertx.core.net.KeyCertOptions;
import io.vertx.core.net.NetClientOptions;
import io.vertx.core.net.TrustOptions;
import io.vertx.mqtt.messages.MqttPublishMessage;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Represents options used by the MQTT client.
 */
@DataObject
@JsonGen(publicConverter = false)
public class MqttClientOptions extends NetClientOptions {

  public static final int DEFAULT_PORT = 1883;
  public static final int DEFAULT_TLS_PORT = 8883;
  /**
   * @deprecated Use {@link #DEFAULT_TLS_PORT} (this constant has a typo in the name)
   */
  @Deprecated
  public static final int DEFAULT_TSL_PORT = DEFAULT_TLS_PORT;
  public static final String DEFAULT_HOST = "localhost";
  /**
   * @deprecated Use {@link MqttClientWillOptions#DEFAULT_WILL_QOS}
   */
  @Deprecated
  public static final int DEFAULT_WILL_QOS = 0;
  public static final int DEFAULT_KEEP_ALIVE_INTERVAL = 30;
  public static final int DEFAULT_MAX_INFLIGHT_QUEUE = 10;
  public static final boolean DEFAULT_CLEAN_SESSION = true;
  /**
   * @deprecated will message is now configured via {@link MqttClientWillOptions}; this constant has no replacement
   */
  @Deprecated
  public static final boolean DEFAULT_WILL_FLAG = false;
  /**
   * @deprecated Use {@link MqttClientWillOptions#DEFAULT_WILL_RETAIN}
   */
  @Deprecated
  public static final boolean DEFAULT_WILL_RETAIN = false;
  public static final int DEFAULT_MAX_MESSAGE_SIZE = -1;
  public static final int DEFAULT_ACK_TIMEOUT = -1;
  public static final boolean DEFAULT_AUTO_ACK = true;
  public static final int DEFAULT_RECV_BYTE_BUF_ALLOCATOR_SIZE = -1;
  public static final int DEFAULT_VERSION = 4;
  public static final Integer DEFAULT_TOPIC_ALIAS_MAXIMUM = 255;
  public static final boolean DEFAULT_AUTO_SERVER_REDIRECT = true;
  public static final boolean DEFAULT_USE_WEB_SOCKET = false;
  public static final String DEFAULT_WEB_SOCKET_PATH = "/mqtt";
  public static final int DEFAULT_WEB_SOCKET_MAX_FRAME_SIZE = 65536;
  public static final long DEFAULT_WEB_SOCKET_HANDSHAKE_TIMEOUT = 10000L;
  public static final boolean DEFAULT_TRY_USE_PER_FRAME_WEB_SOCKET_COMPRESSION = false;
  public static final boolean DEFAULT_TRY_USE_PER_MESSAGE_WEB_SOCKET_COMPRESSION = false;
  public static final int DEFAULT_WEB_SOCKET_COMPRESSION_LEVEL = 6;
  public static final boolean DEFAULT_WEB_SOCKET_COMPRESSION_ALLOW_CLIENT_NO_CONTEXT = false;
  public static final boolean DEFAULT_WEB_SOCKET_COMPRESSION_REQUEST_SERVER_NO_CONTEXT = false;

  private String clientId;
  private String username;
  private String password;
  private MqttClientWillOptions willOptions = new MqttClientWillOptions();
  private boolean cleanSession = DEFAULT_CLEAN_SESSION;
  private int keepAliveInterval = DEFAULT_KEEP_ALIVE_INTERVAL;
  private boolean isAutoKeepAlive = true;
  private boolean isAutoGeneratedClientId = true;
  private int maxInflightQueue = DEFAULT_MAX_INFLIGHT_QUEUE;
  private int maxMessageSize = DEFAULT_MAX_MESSAGE_SIZE;
  private int ackTimeout = DEFAULT_ACK_TIMEOUT;
  private boolean autoAck = DEFAULT_AUTO_ACK;
  private int recvByteBufAllocatorSize = DEFAULT_RECV_BYTE_BUF_ALLOCATOR_SIZE;
  private int version = DEFAULT_VERSION;
  private Long sessionExpireInterval = null;
  private Integer receiveMaximum = null;
  private Long maximumPacketSize = null;
  private Integer topicAliasMaximum = DEFAULT_TOPIC_ALIAS_MAXIMUM;
  private Boolean requestResponseInformation = null;
  private Boolean requestProblemInformation = null;
  private String authenticationMethod = null;
  private Buffer authenticationData = null;
  private boolean autoServerRedirect = DEFAULT_AUTO_SERVER_REDIRECT;
  private boolean useWebSocket = DEFAULT_USE_WEB_SOCKET;
  private String webSocketPath = DEFAULT_WEB_SOCKET_PATH;
  private List<String> webSocketSubProtocols = null;
  private Map<String, String> webSocketHeaders = null;
  private int webSocketMaxFrameSize = DEFAULT_WEB_SOCKET_MAX_FRAME_SIZE;
  private long webSocketHandshakeTimeout = DEFAULT_WEB_SOCKET_HANDSHAKE_TIMEOUT;
  private boolean tryUsePerFrameWebSocketCompression = DEFAULT_TRY_USE_PER_FRAME_WEB_SOCKET_COMPRESSION;
  private boolean tryUsePerMessageWebSocketCompression = DEFAULT_TRY_USE_PER_MESSAGE_WEB_SOCKET_COMPRESSION;
  private int webSocketCompressionLevel = DEFAULT_WEB_SOCKET_COMPRESSION_LEVEL;
  private boolean webSocketCompressionAllowClientNoContext = DEFAULT_WEB_SOCKET_COMPRESSION_ALLOW_CLIENT_NO_CONTEXT;
  private boolean webSocketCompressionRequestServerNoContext = DEFAULT_WEB_SOCKET_COMPRESSION_REQUEST_SERVER_NO_CONTEXT;

  /**
   * Default constructor
   */
  public MqttClientOptions() {
    super();
    init();
  }

  private void init() {
    this.cleanSession = DEFAULT_CLEAN_SESSION;
    this.willOptions = new MqttClientWillOptions();
    this.keepAliveInterval = DEFAULT_KEEP_ALIVE_INTERVAL;
    this.isAutoKeepAlive = true;
    this.isAutoGeneratedClientId = true;
    this.maxInflightQueue = DEFAULT_MAX_INFLIGHT_QUEUE;
    this.maxMessageSize = DEFAULT_MAX_MESSAGE_SIZE;
    this.ackTimeout = DEFAULT_ACK_TIMEOUT;
    this.autoAck = DEFAULT_AUTO_ACK;
    this.recvByteBufAllocatorSize = DEFAULT_RECV_BYTE_BUF_ALLOCATOR_SIZE;
    this.version = DEFAULT_VERSION;
    this.topicAliasMaximum = DEFAULT_TOPIC_ALIAS_MAXIMUM;
    this.useWebSocket = DEFAULT_USE_WEB_SOCKET;
    this.webSocketPath = DEFAULT_WEB_SOCKET_PATH;
    this.webSocketMaxFrameSize = DEFAULT_WEB_SOCKET_MAX_FRAME_SIZE;
    this.webSocketHandshakeTimeout = DEFAULT_WEB_SOCKET_HANDSHAKE_TIMEOUT;
    this.tryUsePerFrameWebSocketCompression = DEFAULT_TRY_USE_PER_FRAME_WEB_SOCKET_COMPRESSION;
    this.tryUsePerMessageWebSocketCompression = DEFAULT_TRY_USE_PER_MESSAGE_WEB_SOCKET_COMPRESSION;
    this.webSocketCompressionLevel = DEFAULT_WEB_SOCKET_COMPRESSION_LEVEL;
    this.webSocketCompressionAllowClientNoContext = DEFAULT_WEB_SOCKET_COMPRESSION_ALLOW_CLIENT_NO_CONTEXT;
    this.webSocketCompressionRequestServerNoContext = DEFAULT_WEB_SOCKET_COMPRESSION_REQUEST_SERVER_NO_CONTEXT;
  }

  /**
   * Create an instance of MqttClientOptions from JSON
   *
   * @param json the JSON
   */
  public MqttClientOptions(JsonObject json) {
    super(json);
    init();
    MqttClientOptionsConverter.fromJson(json, this);
    // Extra backward compat: old "willMessage" string key (pre-willOptions era)
    if (!json.containsKey("willOptions") && !json.containsKey("willMessageBytes") && json.containsKey("willMessage")) {
      this.willOptions.setMessageBytes(Buffer.buffer(json.getString("willMessage")));
    }
  }

  /**
   * Copy constructor
   *
   * @param other the options to copy
   */
  public MqttClientOptions(MqttClientOptions other) {
    super(other);
    this.clientId = other.clientId;
    this.username = other.username;
    this.password = other.password;
    this.willOptions = new MqttClientWillOptions(other.willOptions);
    this.cleanSession = other.cleanSession;
    this.keepAliveInterval = other.keepAliveInterval;
    this.isAutoKeepAlive = other.isAutoKeepAlive;
    this.isAutoGeneratedClientId = other.isAutoGeneratedClientId;
    this.maxInflightQueue = other.maxInflightQueue;
    this.maxMessageSize = other.maxMessageSize;
    this.ackTimeout = other.ackTimeout;
    this.autoAck = other.autoAck;
    this.recvByteBufAllocatorSize = other.recvByteBufAllocatorSize;
    this.version = other.version;
    this.sessionExpireInterval = other.sessionExpireInterval;
    this.receiveMaximum = other.receiveMaximum;
    this.maximumPacketSize = other.maximumPacketSize;
    this.topicAliasMaximum = other.topicAliasMaximum;
    this.requestResponseInformation = other.requestResponseInformation;
    this.requestProblemInformation = other.requestProblemInformation;
    this.authenticationMethod = other.authenticationMethod;
    this.authenticationData = other.authenticationData;
    this.autoServerRedirect = other.autoServerRedirect;
    this.useWebSocket = other.useWebSocket;
    this.webSocketPath = other.webSocketPath;
    this.webSocketSubProtocols = other.webSocketSubProtocols != null ? new ArrayList<>(other.webSocketSubProtocols) : null;
    this.webSocketHeaders = other.webSocketHeaders != null ? new LinkedHashMap<>(other.webSocketHeaders) : null;
    this.webSocketMaxFrameSize = other.webSocketMaxFrameSize;
    this.webSocketHandshakeTimeout = other.webSocketHandshakeTimeout;
    this.tryUsePerFrameWebSocketCompression = other.tryUsePerFrameWebSocketCompression;
    this.tryUsePerMessageWebSocketCompression = other.tryUsePerMessageWebSocketCompression;
    this.webSocketCompressionLevel = other.webSocketCompressionLevel;
    this.webSocketCompressionAllowClientNoContext = other.webSocketCompressionAllowClientNoContext;
    this.webSocketCompressionRequestServerNoContext = other.webSocketCompressionRequestServerNoContext;
  }

  /**
   * @return if username is provided
   */
  public boolean hasUsername() {
    return username != null;
  }

  /**
   * @return if password is provided
   */
  public boolean hasPassword() {
    return password != null;
  }

  /**
   * @return if client wants to start with a clean session
   */
  public boolean isCleanSession() {
    return cleanSession;
  }

  /**
   * @return the will message options object (includes MQTT 5.0 properties)
   */
  public MqttClientWillOptions getWillOptions() {
    return willOptions;
  }

  /**
   * Set the will message options.
   *
   * @param willOptions will options
   * @return current options instance
   */
  public MqttClientOptions setWillOptions(MqttClientWillOptions willOptions) {
    this.willOptions = willOptions != null ? willOptions : new MqttClientWillOptions();
    return this;
  }

  /**
   * @return if the will messages must be retained
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#isRetain()}
   */
  @GenIgnore
  @Deprecated
  public boolean isWillRetain() {
    return willOptions.isRetain();
  }

  /**
   * @return the QoS level for the will message
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#getQos()}
   */
  @GenIgnore
  @Deprecated
  public int getWillQoS() {
    return willOptions.getQos();
  }

  /**
   * @return the keep alive interval (in seconds)
   */
  public int getKeepAliveInterval() {
    return keepAliveInterval;
  }

  /**
   * @return provided username
   */
  public String getUsername() {
    return username;
  }

  /**
   * @return provided password
   */
  public String getPassword() {
    return password;
  }

  /**
   * @return client identifier
   */
  public String getClientId() {
    return clientId;
  }

  /**
   * @return topic on which the will message will be published
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#getTopic()}
   */
  @GenIgnore
  @Deprecated
  public String getWillTopic() {
    return willOptions.getTopic();
  }

  /**
   * @return will message bytes content
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#getMessageBytes()}
   */
  @GenIgnore
  @Deprecated
  public Buffer getWillMessageBytes() {
    return willOptions.getMessageBytes();
  }

  /**
   * Set the client identifier
   *
   * @param clientId client identifier
   * @return current options instance
   */
  public MqttClientOptions setClientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Set the username
   *
   * @param username username
   * @return current options instance
   */
  public MqttClientOptions setUsername(String username) {
    this.username = username;
    return this;
  }

  /**
   * Set the password
   *
   * @param password password
   * @return current options instance
   */
  public MqttClientOptions setPassword(String password) {
    this.password = password;
    return this;
  }

  /**
   * Set the topic on which the will message will be published.
   *
   * @param willTopic topic on which the will message will be published
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setTopic(String)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillTopic(String willTopic) {
    this.willOptions.setTopic(willTopic);
    return this;
  }

  /**
   * Set the content of the will message.
   *
   * @param willMessage content of the will message
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setMessageBytes(Buffer)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillMessageBytes(Buffer willMessage) {
    this.willOptions.setMessageBytes(willMessage);
    return this;
  }

  /**
   * Set to start with a clean session (or not)
   *
   * @param cleanSession if clean session should be activated
   * @return current options instance
   */
  public MqttClientOptions setCleanSession(boolean cleanSession) {
    this.cleanSession = cleanSession;
    return this;
  }

  /**
   * Set the QoS level for the will message.
   *
   * @param willQoS QoS level for the will message
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setQos(int)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillQoS(int willQoS) {
    this.willOptions.setQos(willQoS);
    return this;
  }

  /**
   * Set if the will message must be retained.
   *
   * @param willRetain if the will message must be retained
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setRetain(boolean)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillRetain(boolean willRetain) {
    this.willOptions.setRetain(willRetain);
    return this;
  }

  /**
   * Set the keep alive interval in seconds
   *
   * @param keepAliveInterval keep alive interval in seconds
   * @return current options instance
   */
  public MqttClientOptions setKeepAliveInterval(int keepAliveInterval) {
    if (keepAliveInterval < 1) {
      throw new IllegalArgumentException("Invalid keep alive interval " + keepAliveInterval);
    }
    this.keepAliveInterval = keepAliveInterval;
    return this;
  }

  /**
   * Gets the time in seconds after which the client stops waiting for a PUBACK, PUBREC
   * or PUBCOMP packet from the server in response to a packet it has sent.
   * <p>
   * The default value of this property is 10s.
   *
   * @return timeout in seconds
   */
  public int getAckTimeout() {
    return this.ackTimeout;
  }

  /**
   * Sets the time in seconds after which the client will stop waiting for a PUBACK, PUBREC
   * or PUBCOMP packet from the server in response to a packet it has sent.
   * <p>
   * The default value of this property is -1 which indicates that the client should wait
   * an unlimited time for the server's acknowledgement.
   *
   * @param ackTimeoutSeconds timeout in seconds
   * @return current options instance
   * @throws IllegalArgumentException if the timeout is 0 or &lt; -1.
   */
  public MqttClientOptions setAckTimeout(int ackTimeoutSeconds) {
    if (ackTimeoutSeconds == 0 || ackTimeoutSeconds < -1) {
      throw new IllegalArgumentException("timeout must be > 0 or equal to -1");
    }
    this.ackTimeout = ackTimeoutSeconds;
    return this;
  }

  /**
   * @return max count of unacknowledged messages
   */
  public int getMaxInflightQueue() {
    return maxInflightQueue;
  }

  /**
   * Set max count of unacknowledged messages
   *
   * @param maxInflightQueue max count of unacknowledged messages
   * @return current options instance
   */
  public MqttClientOptions setMaxInflightQueue(int maxInflightQueue) {
    this.maxInflightQueue = maxInflightQueue;
    return this;
  }

  /**
   * Set if the MQTT client must handle PINGREQ automatically
   * (default is true)
   *
   * @param isAutoKeepAlive ping request handled automatically
   * @return current options instance
   */
  public MqttClientOptions setAutoKeepAlive(boolean isAutoKeepAlive) {
    this.isAutoKeepAlive = isAutoKeepAlive;
    return this;
  }

  /**
   * Set if the MQTT client must generate clientId automatically
   * (default is true)
   *
   * @param isAutoGeneratedClientId clientId generated automatically
   * @return current options instance
   */
  public MqttClientOptions setAutoGeneratedClientId(boolean isAutoGeneratedClientId) {
    this.isAutoGeneratedClientId = isAutoGeneratedClientId;
    return this;
  }

  /**
   * @return if the ack (PUBACK/PUBCOMP) will be sent automatically by vertx-mqtt
   */
  public boolean isAutoAck() {
    return autoAck;
  }

  /**
   * Set to false to let the application code to ack the message via {@link MqttPublishMessage#ack()}.
   * If true, the ack (PUBACK/PUBCOMP) will be sent by vertx-mqtt before {@link MqttClient#publishHandler()} execution.
   * (default is true)
   *
   * @param autoAck if the ack (PUBACK/PUBCOMP) will be sent automatically by vertx-mqtt
   * @return current options instance
   */
  public MqttClientOptions setAutoAck(boolean autoAck) {
    this.autoAck = autoAck;
    return this;
  }

  /**
   * @return the size for the FixedRecvByteBufAllocator, or -1 if not set
   */
  public int getRecvByteBufAllocatorSize() {
    return recvByteBufAllocatorSize;
  }

  /**
   * Set the size for the FixedRecvByteBufAllocator used on the channel.
   * Use -1 (default) to leave the allocator unchanged.
   *
   * @param recvByteBufAllocatorSize the fixed buffer size in bytes, or -1 to disable
   * @return current options instance
   */
  public MqttClientOptions setRecvByteBufAllocatorSize(int recvByteBufAllocatorSize) {
    this.recvByteBufAllocatorSize = recvByteBufAllocatorSize;
    return this;
  }

  /**
   * @return if the PINGREQ is handled automatically
   */
  public boolean isAutoKeepAlive() {
    return this.isAutoKeepAlive;
  }

  /**
   * @return if clientId generated automatically
   */
  public boolean isAutoGeneratedClientId() {
    return isAutoGeneratedClientId;
  }

  /**
   * @return max MQTT message size
   */
  public int getMaxMessageSize() {
    return maxMessageSize;
  }

  @Override
  public MqttClientOptions setReceiveBufferSize(int receiveBufferSize) {
    if ((this.maxMessageSize > 0) && (receiveBufferSize > 0)) {
      if (receiveBufferSize < this.maxMessageSize) {
        throw new IllegalArgumentException("Receiver buffer size can't be lower than max message size");
      }
    }
    super.setReceiveBufferSize(receiveBufferSize);
    return this;
  }

  /**
   * Set max MQTT message size
   *
   * @param maxMessageSize max MQTT message size
   * @return MQTT client options instance
   */
  public MqttClientOptions setMaxMessageSize(int maxMessageSize) {
    if (maxMessageSize <= 0 && maxMessageSize != DEFAULT_MAX_MESSAGE_SIZE) {
      throw new IllegalArgumentException("maxMessageSize must be > 0");
    }
    if ((maxMessageSize > 0) && (this.getReceiveBufferSize() > 0)) {
      if (this.getReceiveBufferSize() < maxMessageSize) {
        throw new IllegalArgumentException("Receiver buffer size can't be lower than max message size");
      }
    }
    this.maxMessageSize = maxMessageSize;
    return this;
  }

  public int getVersion() {
    return version;
  }

  public void setVersion(int version) {
    if (version != MqttVersion.MQTT_3_1_1.protocolLevel() && version != MqttVersion.MQTT_5.protocolLevel())
      throw new IllegalArgumentException("Invalid MQTT Version (4 or 5 is accepted)");
    this.version = version;
  }

  public Long getSessionExpireInterval() {
    return sessionExpireInterval;
  }

  public void setSessionExpireInterval(Long sessionExpireInterval) {
    if (sessionExpireInterval != null &&
        (sessionExpireInterval < 0L || sessionExpireInterval > 0xFFFFFFFFL)) {
      throw new IllegalArgumentException("Invalid Session Expire Interval");
    }
    this.sessionExpireInterval = sessionExpireInterval;
  }

  public Integer getReceiveMaximum() {
    return receiveMaximum;
  }

  public void setReceiveMaximum(Integer receiveMaximum) {
    if (receiveMaximum != null &&
        (receiveMaximum < 0L || receiveMaximum > 0xFFFFL)) {
      throw new IllegalArgumentException("Invalid Receive Maximum");
    }
    this.receiveMaximum = receiveMaximum;
  }

  public Long getMaximumPacketSize() {
    return maximumPacketSize;
  }

  public void setMaximumPacketSize(Long maximumPacketSize) {
    if (maximumPacketSize != null &&
        (maximumPacketSize < 0L || maximumPacketSize > 0xFFFFFFFFL)) {
      throw new IllegalArgumentException("Invalid Maximum Packet Size");
    }
    this.maximumPacketSize = maximumPacketSize;
  }

  public Integer getTopicAliasMaximum() {
    return topicAliasMaximum;
  }

  public void setTopicAliasMaximum(Integer topicAliasMaximum) {
    if (topicAliasMaximum != null &&
        (topicAliasMaximum < 0L || topicAliasMaximum > 0xFFFFL)) {
      throw new IllegalArgumentException("Invalid Topic Alias Maximum");
    }
    this.topicAliasMaximum = topicAliasMaximum;
  }

  public Boolean getRequestResponseInformation() {
    return requestResponseInformation;
  }

  public void setRequestResponseInformation(Boolean requestResponseInformation) {
    this.requestResponseInformation = requestResponseInformation;
  }

  public Boolean getRequestProblemInformation() {
    return requestProblemInformation;
  }

  public void setRequestProblemInformation(Boolean requestProblemInformation) {
    this.requestProblemInformation = requestProblemInformation;
  }

  public String getAuthenticationMethod() {
    return authenticationMethod;
  }

  public void setAuthenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
  }

  public Buffer getAuthenticationData() {
    return authenticationData;
  }

  public void setAuthenticationData(Buffer authenticationData) {
    this.authenticationData = authenticationData;
  }

  /**
   * @return whether the client will automatically reconnect to the server indicated
   *         in the SERVER_REFERENCE property of a CONNACK or DISCONNECT packet (MQTT 5.0)
   */
  public boolean isAutoServerRedirect() {
    return autoServerRedirect;
  }

  /**
   * When {@code true} (default) and the broker replies with a CONNACK or DISCONNECT
   * that includes a {@code SERVER_REFERENCE} property (MQTT 5.0 §3.2.2.3.18 / §3.14.2.3.4),
   * the client will transparently reconnect to a server picked at random from the
   * comma-separated list in that property instead of failing.
   *
   * @param autoServerRedirect {@code true} to enable automatic server redirection
   * @return current options instance
   */
  public MqttClientOptions setAutoServerRedirect(boolean autoServerRedirect) {
    this.autoServerRedirect = autoServerRedirect;
    return this;
  }

  /**
   * @return whether the client connects using MQTT over WebSocket
   */
  public boolean isUseWebSocket() {
    return useWebSocket;
  }

  /**
   * Set whether the client connects using MQTT over WebSocket instead of plain TCP. When SSL is enabled
   * the connection uses {@code wss}, otherwise {@code ws}.
   *
   * @param useWebSocket {@code true} to use MQTT over WebSocket
   * @return current options instance
   */
  public MqttClientOptions setUseWebSocket(boolean useWebSocket) {
    this.useWebSocket = useWebSocket;
    return this;
  }

  /**
   * @return the request URI used for the WebSocket handshake
   */
  public String getWebSocketPath() {
    return webSocketPath;
  }

  /**
   * Set the request URI used for the WebSocket handshake, defaults to {@code /mqtt}. The URI can include
   * a query string, for example {@code /mqtt?token=abc}.
   *
   * @param webSocketPath the request URI, must start with {@code /}
   * @return current options instance
   */
  public MqttClientOptions setWebSocketPath(String webSocketPath) {
    if (webSocketPath == null || !webSocketPath.startsWith("/")) {
      throw new IllegalArgumentException("WebSocket path must start with '/'");
    }
    this.webSocketPath = webSocketPath;
    return this;
  }

  /**
   * @return the WebSocket sub-protocols offered during the handshake, or {@code null} when the
   *         sub-protocol is derived from the MQTT version
   */
  public List<String> getWebSocketSubProtocols() {
    return webSocketSubProtocols;
  }

  /**
   * Set the WebSocket sub-protocols offered during the handshake. When not set, the client offers
   * {@code mqttv3.1} for MQTT 3.1 and {@code mqtt} for MQTT 3.1.1 and 5.0, as the specifications require.
   *
   * @param webSocketSubProtocols the sub-protocols
   * @return current options instance
   */
  public MqttClientOptions setWebSocketSubProtocols(List<String> webSocketSubProtocols) {
    this.webSocketSubProtocols = webSocketSubProtocols;
    return this;
  }

  /**
   * Add a WebSocket sub-protocol offered during the handshake.
   *
   * @param subProtocol the sub-protocol
   * @return current options instance
   */
  public MqttClientOptions addWebSocketSubProtocol(String subProtocol) {
    if (webSocketSubProtocols == null) {
      webSocketSubProtocols = new ArrayList<>();
    }
    webSocketSubProtocols.add(subProtocol);
    return this;
  }

  /**
   * @return the additional HTTP headers sent with the WebSocket handshake request
   */
  public Map<String, String> getWebSocketHeaders() {
    return webSocketHeaders;
  }

  /**
   * Set additional HTTP headers sent with the WebSocket handshake request, for example an
   * {@code Authorization} header required by a reverse proxy.
   *
   * @param webSocketHeaders the headers
   * @return current options instance
   */
  public MqttClientOptions setWebSocketHeaders(Map<String, String> webSocketHeaders) {
    this.webSocketHeaders = webSocketHeaders;
    return this;
  }

  /**
   * Add an HTTP header sent with the WebSocket handshake request.
   *
   * @param name the header name
   * @param value the header value
   * @return current options instance
   */
  public MqttClientOptions addWebSocketHeader(String name, String value) {
    if (webSocketHeaders == null) {
      webSocketHeaders = new LinkedHashMap<>();
    }
    webSocketHeaders.put(name, value);
    return this;
  }

  /**
   * @return the WebSocket max frame size
   */
  public int getWebSocketMaxFrameSize() {
    return webSocketMaxFrameSize;
  }

  /**
   * Set the WebSocket max frame size.
   *
   * <p> This should be used when WebSocket transport is used and {@link #getMaxMessageSize()} is larger than the WebSocket frame size
   *
   * @param webSocketMaxFrameSize the new frame size
   * @return current options instance
   */
  public MqttClientOptions setWebSocketMaxFrameSize(int webSocketMaxFrameSize) {
    if (webSocketMaxFrameSize <= 0) {
      throw new IllegalArgumentException("WebSocket max frame size must be > 0");
    }
    this.webSocketMaxFrameSize = webSocketMaxFrameSize;
    return this;
  }

  /**
   * @return the WebSocket handshake timeout in milliseconds
   */
  public long getWebSocketHandshakeTimeout() {
    return webSocketHandshakeTimeout;
  }

  /**
   * Set the time in milliseconds the client waits for the WebSocket handshake to complete before failing the connect,
   * {@code 0} disables the timeout.
   *
   * @param webSocketHandshakeTimeout the timeout in milliseconds
   * @return current options instance
   */
  public MqttClientOptions setWebSocketHandshakeTimeout(long webSocketHandshakeTimeout) {
    if (webSocketHandshakeTimeout < 0) {
      throw new IllegalArgumentException("WebSocket handshake timeout must be >= 0");
    }
    this.webSocketHandshakeTimeout = webSocketHandshakeTimeout;
    return this;
  }

  /**
   * @return {@code true} when the client offers the WebSocket per-frame deflate compression extension
   */
  public boolean isTryUsePerFrameWebSocketCompression() {
    return tryUsePerFrameWebSocketCompression;
  }

  /**
   * Set whether the client offers the WebSocket per-frame deflate compression extension.
   *
   * @param tryUsePerFrameWebSocketCompression {@code true} to offer the extension
   * @return current options instance
   */
  public MqttClientOptions setTryUsePerFrameWebSocketCompression(boolean tryUsePerFrameWebSocketCompression) {
    this.tryUsePerFrameWebSocketCompression = tryUsePerFrameWebSocketCompression;
    return this;
  }

  /**
   * @return {@code true} when the client offers the WebSocket per-message deflate compression extension
   */
  public boolean isTryUsePerMessageWebSocketCompression() {
    return tryUsePerMessageWebSocketCompression;
  }

  /**
   * Set whether the client offers the WebSocket per-message deflate compression extension.
   *
   * @param tryUsePerMessageWebSocketCompression {@code true} to offer the extension
   * @return current options instance
   */
  public MqttClientOptions setTryUsePerMessageWebSocketCompression(boolean tryUsePerMessageWebSocketCompression) {
    this.tryUsePerMessageWebSocketCompression = tryUsePerMessageWebSocketCompression;
    return this;
  }

  /**
   * @return the WebSocket deflate compression level
   */
  public int getWebSocketCompressionLevel() {
    return webSocketCompressionLevel;
  }

  /**
   * Set the WebSocket deflate compression level.
   *
   * @param webSocketCompressionLevel the compression level
   * @return current options instance
   */
  public MqttClientOptions setWebSocketCompressionLevel(int webSocketCompressionLevel) {
    this.webSocketCompressionLevel = webSocketCompressionLevel;
    return this;
  }

  /**
   * @return {@code true} when the client accepts the {@code client_no_context_takeover} parameter of the
   *         per-message deflate compression extension
   */
  public boolean isWebSocketCompressionAllowClientNoContext() {
    return webSocketCompressionAllowClientNoContext;
  }

  /**
   * Set whether the client accepts the {@code client_no_context_takeover} parameter of the per-message
   * deflate compression extension offered by the server.
   *
   * @param webSocketCompressionAllowClientNoContext {@code true} to accept the parameter
   * @return current options instance
   */
  public MqttClientOptions setWebSocketCompressionAllowClientNoContext(boolean webSocketCompressionAllowClientNoContext) {
    this.webSocketCompressionAllowClientNoContext = webSocketCompressionAllowClientNoContext;
    return this;
  }

  /**
   * @return {@code true} when the client requests the {@code server_no_context_takeover} parameter of the
   *         per-message deflate compression extension
   */
  public boolean isWebSocketCompressionRequestServerNoContext() {
    return webSocketCompressionRequestServerNoContext;
  }

  /**
   * Set whether the client requests the {@code server_no_context_takeover} parameter of the per-message
   * deflate compression extension.
   *
   * @param webSocketCompressionRequestServerNoContext {@code true} to request the parameter
   * @return current options instance
   */
  public MqttClientOptions setWebSocketCompressionRequestServerNoContext(boolean webSocketCompressionRequestServerNoContext) {
    this.webSocketCompressionRequestServerNoContext = webSocketCompressionRequestServerNoContext;
    return this;
  }

  @Override
  public MqttClientOptions setSsl(boolean ssl) {
    super.setSsl(ssl);
    return this;
  }

  @Override
  public MqttClientOptions setHostnameVerificationAlgorithm(String hostnameVerificationAlgorithm) {
    return (MqttClientOptions) super.setHostnameVerificationAlgorithm(hostnameVerificationAlgorithm);
  }

  @Override
  public MqttClientOptions setTrustAll(boolean trustAll) {
    super.setTrustAll(trustAll);
    return this;
  }

  @Override
  public MqttClientOptions setKeyCertOptions(KeyCertOptions options) {
    super.setKeyCertOptions(options);
    return this;
  }

  @Override
  public MqttClientOptions setTrustOptions(TrustOptions options) {
    super.setTrustOptions(options);
    return this;
  }

  @Override
  public MqttClientOptions addEnabledCipherSuite(String suite) {
    super.addEnabledCipherSuite(suite);
    return this;
  }

  @Override
  public MqttClientOptions addEnabledSecureTransportProtocol(String protocol) {
    super.addEnabledSecureTransportProtocol(protocol);
    return this;
  }

  @Override
  public MqttClientOptions addCrlPath(String crlPath) throws NullPointerException {
    super.addCrlPath(crlPath);
    return this;
  }

  @Override
  public MqttClientOptions addCrlValue(Buffer crlValue) throws NullPointerException {
    super.addCrlValue(crlValue);
    return this;
  }

  @Override
  public JsonObject toJson() {
    JsonObject json = super.toJson();
    MqttClientOptionsConverter.toJson(this, json);
    return json;
  }

  @Override
  public String toString() {
    return "Options {" +
      "clientId='" + clientId + '\'' +
      ", username='" + username + '\'' +
      ", password='" + password + '\'' +
      ", will=" + willOptions +
      ", cleanSession=" + cleanSession +
      ", keepAliveTimeSeconds=" + keepAliveInterval +
      ", isAutoKeepAlive=" + isAutoKeepAlive +
      ", isAutoGeneratedClientId=" + isAutoGeneratedClientId +
      ", isAutoAck=" + autoAck +
      ", version=" + version +
      ", sessionExpireInterval=" + sessionExpireInterval +
      ", receiveMaximum=" + receiveMaximum +
      ", maximumPacketSize=" + maximumPacketSize +
      ", topicAliasMaximum=" + topicAliasMaximum +
      ", requestResponseInformation=" + requestResponseInformation +
      ", requestProblemInformation=" + requestProblemInformation +
      ", authenticationMethod=" + authenticationMethod +
      ", authenticationData=" + (authenticationData != null ? "[" + authenticationData.length() + " bytes]" : "null") +
      ", autoServerRedirect=" + autoServerRedirect +
      ", useWebSocket=" + useWebSocket +
      '}';
  }
}
