/*
 * Copyright 2016 Red Hat Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.vertx.mqtt;

import io.netty.handler.codec.mqtt.MqttVersion;
import io.vertx.codegen.annotations.DataObject;
import io.vertx.codegen.annotations.GenIgnore;
import io.vertx.codegen.json.annotations.JsonGen;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonObject;
import io.vertx.core.net.KeyCertOptions;
import io.vertx.core.net.NetClientOptions;
import io.vertx.core.net.TrustOptions;
import io.vertx.mqtt.messages.MqttPublishMessage;

/**
 * Represents options used by the MQTT client.
 */
@DataObject
@JsonGen(publicConverter = false)
public class MqttClientOptions extends NetClientOptions {

  public static final int DEFAULT_PORT = 1883;
  public static final int DEFAULT_TLS_PORT = 8883;
  /**
   * @deprecated Use {@link #DEFAULT_TLS_PORT} (this constant has a typo in the name)
   */
  @Deprecated
  public static final int DEFAULT_TSL_PORT = DEFAULT_TLS_PORT;
  public static final String DEFAULT_HOST = "localhost";
  /**
   * @deprecated Use {@link MqttClientWillOptions#DEFAULT_WILL_QOS}
   */
  @Deprecated
  public static final int DEFAULT_WILL_QOS = 0;
  public static final int DEFAULT_KEEP_ALIVE_INTERVAL = 30;
  public static final int DEFAULT_MAX_INFLIGHT_QUEUE = 10;
  public static final boolean DEFAULT_CLEAN_SESSION = true;
  /**
   * @deprecated will message is now configured via {@link MqttClientWillOptions}; this constant has no replacement
   */
  @Deprecated
  public static final boolean DEFAULT_WILL_FLAG = false;
  /**
   * @deprecated Use {@link MqttClientWillOptions#DEFAULT_WILL_RETAIN}
   */
  @Deprecated
  public static final boolean DEFAULT_WILL_RETAIN = false;
  public static final int DEFAULT_MAX_MESSAGE_SIZE = -1;
  public static final int DEFAULT_ACK_TIMEOUT = -1;
  public static final boolean DEFAULT_AUTO_ACK = true;
  public static final int DEFAULT_RECV_BYTE_BUF_ALLOCATOR_SIZE = -1;
  public static final int DEFAULT_VERSION = 4;
  public static final Integer DEFAULT_TOPIC_ALIAS_MAXIMUM = 255;
  public static final boolean DEFAULT_AUTO_SERVER_REDIRECT = true;

  private String clientId;
  private String username;
  private String password;
  private MqttClientWillOptions willOptions = new MqttClientWillOptions();
  private boolean cleanSession = DEFAULT_CLEAN_SESSION;
  private int keepAliveInterval = DEFAULT_KEEP_ALIVE_INTERVAL;
  private boolean isAutoKeepAlive = true;
  private boolean isAutoGeneratedClientId = true;
  private int maxInflightQueue = DEFAULT_MAX_INFLIGHT_QUEUE;
  private int maxMessageSize = DEFAULT_MAX_MESSAGE_SIZE;
  private int ackTimeout = DEFAULT_ACK_TIMEOUT;
  private boolean autoAck = DEFAULT_AUTO_ACK;
  private int recvByteBufAllocatorSize = DEFAULT_RECV_BYTE_BUF_ALLOCATOR_SIZE;
  private int version = DEFAULT_VERSION;
  private Long sessionExpireInterval = null;
  private Integer receiveMaximum = null;
  private Long maximumPacketSize = null;
  private Integer topicAliasMaximum = DEFAULT_TOPIC_ALIAS_MAXIMUM;
  private Boolean requestResponseInformation = null;
  private Boolean requestProblemInformation = null;
  private String authenticationMethod = null;
  private Buffer authenticationData = null;
  private boolean autoServerRedirect = DEFAULT_AUTO_SERVER_REDIRECT;

  /**
   * Default constructor
   */
  public MqttClientOptions() {
    super();
    init();
  }

  private void init() {
    this.cleanSession = DEFAULT_CLEAN_SESSION;
    this.willOptions = new MqttClientWillOptions();
    this.keepAliveInterval = DEFAULT_KEEP_ALIVE_INTERVAL;
    this.isAutoKeepAlive = true;
    this.isAutoGeneratedClientId = true;
    this.maxInflightQueue = DEFAULT_MAX_INFLIGHT_QUEUE;
    this.maxMessageSize = DEFAULT_MAX_MESSAGE_SIZE;
    this.ackTimeout = DEFAULT_ACK_TIMEOUT;
    this.autoAck = DEFAULT_AUTO_ACK;
    this.recvByteBufAllocatorSize = DEFAULT_RECV_BYTE_BUF_ALLOCATOR_SIZE;
    this.version = DEFAULT_VERSION;
    this.topicAliasMaximum = DEFAULT_TOPIC_ALIAS_MAXIMUM;
  }

  /**
   * Create an instance of MqttClientOptions from JSON
   *
   * @param json the JSON
   */
  public MqttClientOptions(JsonObject json) {
    super(json);
    init();
    MqttClientOptionsConverter.fromJson(json, this);
    // Extra backward compat: old "willMessage" string key (pre-willOptions era)
    if (!json.containsKey("willOptions") && !json.containsKey("willMessageBytes") && json.containsKey("willMessage")) {
      this.willOptions.setMessageBytes(Buffer.buffer(json.getString("willMessage")));
    }
  }

  /**
   * Copy constructor
   *
   * @param other the options to copy
   */
  public MqttClientOptions(MqttClientOptions other) {
    super(other);
    this.clientId = other.clientId;
    this.username = other.username;
    this.password = other.password;
    this.willOptions = new MqttClientWillOptions(other.willOptions);
    this.cleanSession = other.cleanSession;
    this.keepAliveInterval = other.keepAliveInterval;
    this.isAutoKeepAlive = other.isAutoKeepAlive;
    this.isAutoGeneratedClientId = other.isAutoGeneratedClientId;
    this.maxInflightQueue = other.maxInflightQueue;
    this.maxMessageSize = other.maxMessageSize;
    this.ackTimeout = other.ackTimeout;
    this.autoAck = other.autoAck;
    this.recvByteBufAllocatorSize = other.recvByteBufAllocatorSize;
    this.version = other.version;
    this.sessionExpireInterval = other.sessionExpireInterval;
    this.receiveMaximum = other.receiveMaximum;
    this.maximumPacketSize = other.maximumPacketSize;
    this.topicAliasMaximum = other.topicAliasMaximum;
    this.requestResponseInformation = other.requestResponseInformation;
    this.requestProblemInformation = other.requestProblemInformation;
    this.authenticationMethod = other.authenticationMethod;
    this.authenticationData = other.authenticationData;
    this.autoServerRedirect = other.autoServerRedirect;
  }

  /**
   * @return if username is provided
   */
  public boolean hasUsername() {
    return username != null;
  }

  /**
   * @return if password is provided
   */
  public boolean hasPassword() {
    return password != null;
  }

  /**
   * @return if client wants to start with a clean session
   */
  public boolean isCleanSession() {
    return cleanSession;
  }

  /**
   * @return the will message options object (includes MQTT 5.0 properties)
   */
  public MqttClientWillOptions getWillOptions() {
    return willOptions;
  }

  /**
   * Set the will message options.
   *
   * @param willOptions will options
   * @return current options instance
   */
  public MqttClientOptions setWillOptions(MqttClientWillOptions willOptions) {
    this.willOptions = willOptions != null ? willOptions : new MqttClientWillOptions();
    return this;
  }

  /**
   * @return if the will messages must be retained
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#isRetain()}
   */
  @GenIgnore
  @Deprecated
  public boolean isWillRetain() {
    return willOptions.isRetain();
  }

  /**
   * @return the QoS level for the will message
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#getQos()}
   */
  @GenIgnore
  @Deprecated
  public int getWillQoS() {
    return willOptions.getQos();
  }

  /**
   * @return the keep alive interval (in seconds)
   */
  public int getKeepAliveInterval() {
    return keepAliveInterval;
  }

  /**
   * @return provided username
   */
  public String getUsername() {
    return username;
  }

  /**
   * @return provided password
   */
  public String getPassword() {
    return password;
  }

  /**
   * @return client identifier
   */
  public String getClientId() {
    return clientId;
  }

  /**
   * @return topic on which the will message will be published
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#getTopic()}
   */
  @GenIgnore
  @Deprecated
  public String getWillTopic() {
    return willOptions.getTopic();
  }

  /**
   * @return will message bytes content
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#getMessageBytes()}
   */
  @GenIgnore
  @Deprecated
  public Buffer getWillMessageBytes() {
    return willOptions.getMessageBytes();
  }

  /**
   * Set the client identifier
   *
   * @param clientId client identifier
   * @return current options instance
   */
  public MqttClientOptions setClientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Set the username
   *
   * @param username username
   * @return current options instance
   */
  public MqttClientOptions setUsername(String username) {
    this.username = username;
    return this;
  }

  /**
   * Set the password
   *
   * @param password password
   * @return current options instance
   */
  public MqttClientOptions setPassword(String password) {
    this.password = password;
    return this;
  }

  /**
   * Set the topic on which the will message will be published.
   *
   * @param willTopic topic on which the will message will be published
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setTopic(String)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillTopic(String willTopic) {
    this.willOptions.setTopic(willTopic);
    return this;
  }

  /**
   * Set the content of the will message.
   *
   * @param willMessage content of the will message
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setMessageBytes(Buffer)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillMessageBytes(Buffer willMessage) {
    this.willOptions.setMessageBytes(willMessage);
    return this;
  }

  /**
   * Set to start with a clean session (or not)
   *
   * @param cleanSession if clean session should be activated
   * @return current options instance
   */
  public MqttClientOptions setCleanSession(boolean cleanSession) {
    this.cleanSession = cleanSession;
    return this;
  }

  /**
   * Set the QoS level for the will message.
   *
   * @param willQoS QoS level for the will message
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setQos(int)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillQoS(int willQoS) {
    this.willOptions.setQos(willQoS);
    return this;
  }

  /**
   * Set if the will message must be retained.
   *
   * @param willRetain if the will message must be retained
   * @return current options instance
   * @deprecated Use {@link #getWillOptions()} and {@link MqttClientWillOptions#setRetain(boolean)}
   */
  @GenIgnore
  @Deprecated
  public MqttClientOptions setWillRetain(boolean willRetain) {
    this.willOptions.setRetain(willRetain);
    return this;
  }

  /**
   * Set the keep alive interval in seconds
   *
   * @param keepAliveInterval keep alive interval in seconds
   * @return current options instance
   */
  public MqttClientOptions setKeepAliveInterval(int keepAliveInterval) {
    if (keepAliveInterval < 1) {
      throw new IllegalArgumentException("Invalid keep alive interval " + keepAliveInterval);
    }
    this.keepAliveInterval = keepAliveInterval;
    return this;
  }

  /**
   * Gets the time in seconds after which the client stops waiting for a PUBACK, PUBREC
   * or PUBCOMP packet from the server in response to a packet it has sent.
   * <p>
   * The default value of this property is 10s.
   *
   * @return timeout in seconds
   */
  public int getAckTimeout() {
    return this.ackTimeout;
  }

  /**
   * Sets the time in seconds after which the client will stop waiting for a PUBACK, PUBREC
   * or PUBCOMP packet from the server in response to a packet it has sent.
   * <p>
   * The default value of this property is -1 which indicates that the client should wait
   * an unlimited time for the server's acknowledgement.
   *
   * @param ackTimeoutSeconds timeout in seconds
   * @return current options instance
   * @throws IllegalArgumentException if the timeout is 0 or &lt; -1.
   */
  public MqttClientOptions setAckTimeout(int ackTimeoutSeconds) {
    if (ackTimeoutSeconds == 0 || ackTimeoutSeconds < -1) {
      throw new IllegalArgumentException("timeout must be > 0 or equal to -1");
    }
    this.ackTimeout = ackTimeoutSeconds;
    return this;
  }

  /**
   * @return max count of unacknowledged messages
   */
  public int getMaxInflightQueue() {
    return maxInflightQueue;
  }

  /**
   * Set max count of unacknowledged messages
   * 
   * @param maxInflightQueue max count of unacknowledged messages
   * @return current options instance
   */
  public MqttClientOptions setMaxInflightQueue(int maxInflightQueue) {
    this.maxInflightQueue = maxInflightQueue;
    return this;
  }

  /**
   * Set if the MQTT client must handle PINGREQ automatically
   * (default is true)
   *
   * @param isAutoKeepAlive ping request handled automatically
   * @return current options instance
   */
  public MqttClientOptions setAutoKeepAlive(boolean isAutoKeepAlive) {
    this.isAutoKeepAlive = isAutoKeepAlive;
    return this;
  }

  /**
   * Set if the MQTT client must generate clientId automatically
   * (default is true)
   *
   * @param isAutoGeneratedClientId clientId generated automatically
   * @return current options instance
   */
  public MqttClientOptions setAutoGeneratedClientId(boolean isAutoGeneratedClientId) {
    this.isAutoGeneratedClientId = isAutoGeneratedClientId;
    return this;
  }

  /**
   * @return if the ack (PUBACK/PUBCOMP) will be sent automatically by vertx-mqtt
   */
  public boolean isAutoAck() {
    return autoAck;
  }

  /**
   * Set to false to let the application code to ack the message via {@link MqttPublishMessage#ack()}.
   * If true, the ack (PUBACK/PUBCOMP) will be sent by vertx-mqtt before {@link MqttClient#publishHandler()} execution.
   * (default is true)
   * 
   * @param autoAck if the ack (PUBACK/PUBCOMP) will be sent automatically by vertx-mqtt
   * @return current options instance
   */
  public MqttClientOptions setAutoAck(boolean autoAck) {
    this.autoAck = autoAck;
    return this;
  }

  /**
   * @return the size for the FixedRecvByteBufAllocator, or -1 if not set
   */
  public int getRecvByteBufAllocatorSize() {
    return recvByteBufAllocatorSize;
  }

  /**
   * Set the size for the FixedRecvByteBufAllocator used on the channel.
   * Use -1 (default) to leave the allocator unchanged.
   *
   * @param recvByteBufAllocatorSize the fixed buffer size in bytes, or -1 to disable
   * @return current options instance
   */
  public MqttClientOptions setRecvByteBufAllocatorSize(int recvByteBufAllocatorSize) {
    this.recvByteBufAllocatorSize = recvByteBufAllocatorSize;
    return this;
  }

  /**
   * @return if the PINGREQ is handled automatically
   */
  public boolean isAutoKeepAlive() {
    return this.isAutoKeepAlive;
  }

  /**
   * @return if clientId generated automatically
   */
  public boolean isAutoGeneratedClientId() {
    return isAutoGeneratedClientId;
  }

  /**
   * @return max MQTT message size
   */
  public int getMaxMessageSize() {
    return maxMessageSize;
  }

  @Override
  public MqttClientOptions setReceiveBufferSize(int receiveBufferSize) {
    if ((this.maxMessageSize > 0) && (receiveBufferSize > 0)) {
      if (receiveBufferSize < this.maxMessageSize) {
        throw new IllegalArgumentException("Receiver buffer size can't be lower than max message size");
      }
    }
    super.setReceiveBufferSize(receiveBufferSize);
    return this;
  }

  /**
   * Set max MQTT message size
   *
   * @param maxMessageSize max MQTT message size
   * @return MQTT client options instance
   */
  public MqttClientOptions setMaxMessageSize(int maxMessageSize) {
    if (maxMessageSize <= 0 && maxMessageSize != DEFAULT_MAX_MESSAGE_SIZE) {
      throw new IllegalArgumentException("maxMessageSize must be > 0");
    }
    if ((maxMessageSize > 0) && (this.getReceiveBufferSize() > 0)) {
      if (this.getReceiveBufferSize() < maxMessageSize) {
        throw new IllegalArgumentException("Receiver buffer size can't be lower than max message size");
      }
    }
    this.maxMessageSize = maxMessageSize;
    return this;
  }

  public int getVersion() {
    return version;
  }

  public void setVersion(int version) {
    if (version != MqttVersion.MQTT_3_1_1.protocolLevel() && version != MqttVersion.MQTT_5.protocolLevel())
      throw new IllegalArgumentException("Invalid MQTT Version (4 or 5 is accepted)");
    this.version = version;
  }

  public Long getSessionExpireInterval() {
    return sessionExpireInterval;
  }

  public void setSessionExpireInterval(Long sessionExpireInterval) {
    if (sessionExpireInterval != null &&
        (sessionExpireInterval < 0L || sessionExpireInterval > 0xFFFFFFFFL)) {
      throw new IllegalArgumentException("Invalid Session Expire Interval");
    }
    this.sessionExpireInterval = sessionExpireInterval;
  }

  public Integer getReceiveMaximum() {
    return receiveMaximum;
  }

  public void setReceiveMaximum(Integer receiveMaximum) {
    if (receiveMaximum != null &&
        (receiveMaximum < 0L || receiveMaximum > 0xFFFFL)) {
      throw new IllegalArgumentException("Invalid Receive Maximum");
    }
    this.receiveMaximum = receiveMaximum;
  }

  public Long getMaximumPacketSize() {
    return maximumPacketSize;
  }

  public void setMaximumPacketSize(Long maximumPacketSize) {
    if (maximumPacketSize != null &&
        (maximumPacketSize < 0L || maximumPacketSize > 0xFFFFFFFFL)) {
      throw new IllegalArgumentException("Invalid Maximum Packet Size");
    }
    this.maximumPacketSize = maximumPacketSize;
  }

  public Integer getTopicAliasMaximum() {
    return topicAliasMaximum;
  }

  public void setTopicAliasMaximum(Integer topicAliasMaximum) {
    if (topicAliasMaximum != null &&
        (topicAliasMaximum < 0L || topicAliasMaximum > 0xFFFFL)) {
      throw new IllegalArgumentException("Invalid Topic Alias Maximum");
    }
    this.topicAliasMaximum = topicAliasMaximum;
  }

  public Boolean getRequestResponseInformation() {
    return requestResponseInformation;
  }

  public void setRequestResponseInformation(Boolean requestResponseInformation) {
    this.requestResponseInformation = requestResponseInformation;
  }

  public Boolean getRequestProblemInformation() {
    return requestProblemInformation;
  }

  public void setRequestProblemInformation(Boolean requestProblemInformation) {
    this.requestProblemInformation = requestProblemInformation;
  }

  public String getAuthenticationMethod() {
    return authenticationMethod;
  }

  public void setAuthenticationMethod(String authenticationMethod) {
    this.authenticationMethod = authenticationMethod;
  }

  public Buffer getAuthenticationData() {
    return authenticationData;
  }

  public void setAuthenticationData(Buffer authenticationData) {
    this.authenticationData = authenticationData;
  }

  /**
   * @return whether the client will automatically reconnect to the server indicated
   *         in the SERVER_REFERENCE property of a CONNACK or DISCONNECT packet (MQTT 5.0)
   */
  public boolean isAutoServerRedirect() {
    return autoServerRedirect;
  }

  /**
   * When {@code true} (default) and the broker replies with a CONNACK or DISCONNECT
   * that includes a {@code SERVER_REFERENCE} property (MQTT 5.0 §3.2.2.3.18 / §3.14.2.3.4),
   * the client will transparently reconnect to a server picked at random from the
   * comma-separated list in that property instead of failing.
   *
   * @param autoServerRedirect {@code true} to enable automatic server redirection
   * @return current options instance
   */
  public MqttClientOptions setAutoServerRedirect(boolean autoServerRedirect) {
    this.autoServerRedirect = autoServerRedirect;
    return this;
  }

  @Override
  public MqttClientOptions setSsl(boolean ssl) {
    super.setSsl(ssl);
    return this;
  }

  @Override
  public MqttClientOptions setHostnameVerificationAlgorithm(String hostnameVerificationAlgorithm) {
    return (MqttClientOptions) super.setHostnameVerificationAlgorithm(hostnameVerificationAlgorithm);
  }

  @Override
  public MqttClientOptions setTrustAll(boolean trustAll) {
    super.setTrustAll(trustAll);
    return this;
  }

  @Override
  public MqttClientOptions setKeyCertOptions(KeyCertOptions options) {
    super.setKeyCertOptions(options);
    return this;
  }

  @Override
  public MqttClientOptions setTrustOptions(TrustOptions options) {
    super.setTrustOptions(options);
    return this;
  }

  @Override
  public MqttClientOptions addEnabledCipherSuite(String suite) {
    super.addEnabledCipherSuite(suite);
    return this;
  }

  @Override
  public MqttClientOptions addEnabledSecureTransportProtocol(String protocol) {
    super.addEnabledSecureTransportProtocol(protocol);
    return this;
  }

  @Override
  public MqttClientOptions addCrlPath(String crlPath) throws NullPointerException {
    super.addCrlPath(crlPath);
    return this;
  }

  @Override
  public MqttClientOptions addCrlValue(Buffer crlValue) throws NullPointerException {
    super.addCrlValue(crlValue);
    return this;
  }

  @Override
  public JsonObject toJson() {
    JsonObject json = super.toJson();
    MqttClientOptionsConverter.toJson(this, json);
    return json;
  }

  @Override
  public String toString() {
    return "Options {" +
      "clientId='" + clientId + '\'' +
      ", username='" + username + '\'' +
      ", password='" + password + '\'' +
      ", will=" + willOptions +
      ", cleanSession=" + cleanSession +
      ", keepAliveTimeSeconds=" + keepAliveInterval +
      ", isAutoKeepAlive=" + isAutoKeepAlive +
      ", isAutoGeneratedClientId=" + isAutoGeneratedClientId +
      ", isAutoAck=" + autoAck +
      ", version=" + version +
      ", sessionExpireInterval=" + sessionExpireInterval +
      ", receiveMaximum=" + receiveMaximum +
      ", maximumPacketSize=" + maximumPacketSize +
      ", topicAliasMaximum=" + topicAliasMaximum +
      ", requestResponseInformation=" + requestResponseInformation +
      ", requestProblemInformation=" + requestProblemInformation +
      ", authenticationMethod=" + authenticationMethod +
      ", authenticationData=" + (authenticationData != null ? "[" + authenticationData.length() + " bytes]" : "null") +
      ", autoServerRedirect=" + autoServerRedirect +
      '}';
  }
}
