/*
 * Copyright 2016 Red Hat Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.vertx.mqtt.it;

import io.netty.handler.codec.mqtt.MqttVersion;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.mqtt.MqttClientOptions;
import org.junit.Before;
import org.junit.runner.RunWith;
import org.testcontainers.containers.BindMode;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

/**
 * Base class for MQTT 5.0 integration tests running against a real Mosquitto 2.x broker.
 * The broker is started via Testcontainers using the same {@code mosquitto.conf} used by
 * the existing integration tests ({@code allow_anonymous true}, port 1883).
 */
@RunWith(VertxUnitRunner.class)
public abstract class Mqtt5ClientBaseIT {

  public GenericContainer<?> mosquitto = new GenericContainer<>(DockerImageName.parse("eclipse-mosquitto:2.0.12"))
    .withExposedPorts(1883)
    .withClasspathResourceMapping("it/mosquitto.conf", "/mosquitto/config/mosquitto.conf", BindMode.READ_ONLY)
    .waitingFor(Wait.forLogMessage(".*mosquitto .* running.*", 1));

  protected int port;
  protected String host;

  @Before
  public void setUp() {
    mosquitto.start();
    port = mosquitto.getMappedPort(1883);
    host = mosquitto.getHost();
  }

  protected MqttClientOptions v5Options() {
    MqttClientOptions opts = new MqttClientOptions();
    opts.setVersion(MqttVersion.MQTT_5.protocolLevel());
    opts.setAutoGeneratedClientId(true);
    return opts;
  }
}
