name: CI client_mqtt5

on:
  push:
    branches:
      - client_mqtt5
  pull_request:
    branches:
      - client_mqtt5

jobs:
  CI:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Run tests
        run: mvn -s .github/maven-ci-settings.xml -q clean verify -B
